### ISSUE TITLE
Request: Provide generic progress event/callback

### ISSUE THREAD

**Issue by lwansbrough** [oblador/react-native-image-progress#1]
For those of us who may have a completely different idea of how to show the progress indicator (and to save you from serving requests for different styles) you might consider adding a generic callback and/or event in the forms:

```javascript
<Image indicator={(progress) => console.log(`${Math.round(progress * 100)}%`)}/>
```

or

```javascript
<Image ref="blah"/>
...
this.refs.blah.on('progress', (progress) => console.log(`${Math.round(progress * 100)}%`));
```

Nice work so far! :)

**Comment by oblador** [comment]
This has been on my todo and now you have both! :-) 

Put it as a `renderIndicator` property for clarity. For progress events you can use `onLoadProgress(event)` etc.

**Comment by lwansbrough** [comment]
Awesome, thanks!
