### ISSUE TITLE
do you have a progress percent example?

### ISSUE THREAD

**Issue by faceyspacey** [oblador/react-native-image-progress#14]
i.e. using the `renderIndicator` callback's `progress` parameter?

**Comment by oblador** [comment]
Not sure what you mean, did you try something as simple as `Math.round(progress * 100) + '%'`?

**Comment by faceyspacey** [comment]
I figured it out. Would you say that image loading progress is so unreliable that it's not worth using at all?

**Comment by oblador** [comment]
No, it's gotten better. Android doesn't have support for progress though.

**Comment by faceyspacey** [comment]
that's funny, i used it last week, and i forget what happened exactly, but i was like "this is utter trash." I think i only got lie 2-3 calls to my handler, and I think they they were just at the end. You need more, and to have them evenly spread out to be useful. Perhaps its cuz i was developing locally. What are your thoughts on this?

**Comment by oblador** [comment]
If you are fetching assets locally there's not much use for a progress indicator no?

**Comment by faceyspacey** [comment]
i meant locally from my computer until i have ones coming from over the web. ...but i'll test and see. the issue is probably simply this.
