### ISSUE TITLE
Text within Image gets hidden after Image is loaded

### ISSUE THREAD

**Issue by alvinwoon** [oblador/react-native-image-progress#2]
If you have something like
```
<Image>
    <Text />
</Image>
```
The text will get hidden after Image is loaded

**Comment by oblador** [comment]
I thought I solved that in 0.1.1, what version are you using?

**Comment by alvinwoon** [comment]
oops. nevermind. i am on 0.1.0. Is the latest version out on npm? Just did a npm update and it can't find the repo. 

Thanks!

**Comment by oblador** [comment]
Oops on my side, forgot to publish on npm... :disappointed: 

Should work now!

**Comment by alvinwoon** [comment]
Works. Awesome!
