### ISSUE TITLE
Change the source uri if image not exists

### ISSUE THREAD

**Issue by fbonesso** [oblador/react-native-image-progress#22]
Hi folks,

There is some way to do that? I'm trying with onError method but the image still loading.

Thanks!

**Comment by fbonesso** [comment]
This is what I'm trying to do:

`
<Image source={{ uri: photo }} onError={(e) => { this.props.source = { uri: 'https://example.domain.com/no-photo.png' }}} />`

**Comment by srkirkland** [comment]
@fbonesso What I did was wrap it in a component and just render a default/secondary image only on failure.  

So

`<Image source={{ uri: photo }} onError={this._onError} />`

then 

`_onError = () => { this.setState({ failed: true }); }`

then just in your render function 

`if (this.state.failed) return defaultImage;`

I know it's super simple but that way I can use this library to show a loading progress bar, and if the image fails to load it'll throw in the default image I provide.

**Comment by oblador** [comment]
Yes this approach should work, the problem with the OP's code was that it was trying to change `this.props` which is a no-go in react.

**Comment by RoiDayan1** [comment]
hi
maybe this is what are you looking for:

<Image ref={img_unique_id} source={{uri: "http://some_broken_url"}} style={{flex: 1, resizeMode: 'stretch'}} onError={(e) => this.refs[img_unique_id].setNativeProps({src: [{uri: "http://some_working_url"}]})}/>

**Comment by anuragprajapat** [comment]
@RoiDayan1 
Did not work for me! 
undefined is not an object (evaluating this.refs[myid].setNativeProps)

**Comment by ducpt2** [comment]
Hi all,
I have list uri of image in assets, how can i check if uri exist or not? I research but can not find a solution.

**Comment by zurez** [comment]
Same question.
Convert Image prop to use src if uri is broken.

**Comment by galcivar** [comment]
Need the same functionality, I have a list of images and I need to dinamically update each if there's an error loading one of them with an alternative link (the link is different for each image).

Tried @RoiDayan1 method, but got the same as @anuragprajapat:
undefined is not an object (evaluating this.refs[myid].setNativeProps)

**Comment by Dror-Bar** [comment]
Very simple solution using OnError and State:
`<Image source={{ uri: this.state.uri }} onError={() => this.setState({ uri: "new uri" })} />`


Alternatively, using situational JSX expression:
```
{this.state.noError && <Image source={{ uri: "http://some_broken_url" }} onError={() => this.setState({ noError: true })} />}
{!this.state.noError && <Image source={require("path_to_image.png")} />}
```

**Comment by oblador** [comment]
You can also use [`defaultSource`](https://facebook.github.io/react-native/docs/image.html#defaultsource) for this functionality.

**Comment by maneeshprajapati** [comment]
@oblador [defaultSource](https://facebook.github.io/react-native/docs/image.html#defaultsource) works like charm.

**Comment by Dror-Bar** [comment]
Yes that seems to be the ideal solution right now.

onError does have one advantage though, that you can notify other components whether you successfully loaded the original uri or not, and have different behaviour depending on this.

**Comment by NarendraSingh88** [comment]
@Dror-Bar @srkirkland how to do that in case of image-url arrays. Not getting any way for that :(

**Comment by GavinThomas1192** [comment]
> You can also use [`defaultSource`](https://facebook.github.io/react-native/docs/image.html#defaultsource) for this functionality.

This should be at top!

**Comment by unmec** [comment]
@RoiDayan1 solution is the best for customization I think. Just set up ref and we can control exactly each image element's source in case of error.

There is a drawback however, say with the code below for instance:
```
onError={() => this.ImgRefs[img_unique_id].setNativeProps({src: [{uri: this.state.workingUri}]})}
``` 
the state of workingUri will be set only once when onError occurs, after that, it will not reflect any new change when you set state for workingUri.

In addition, remember replace "src" with "source" if you are working with iOS.

**Comment by Luccasoli** [comment]
When the uri its a invalid network url, onError is not triggered :(

**Comment by krunalray** [comment]
> hi
> maybe this is what are you looking for:
> 
> <Image ref={img_unique_id} source={{uri: "http://some_broken_url"}} style={{flex: 1, resizeMode: 'stretch'}} onError={(e) => this.refs[img_unique_id].setNativeProps({src: [{uri: "http://some_working_url"}]})}/>

Thank you it's work for me.

**Comment by Patrickism** [comment]
Try adding this, it worked for me. :) 
import { Image } from 'react-native'
