### ISSUE TITLE
Progress bar regresses

### ISSUE THREAD

**Issue by herve1976** [oblador/react-native-image-progress#27]
During the loading the progress regresses backward sometimes. Does it know the total image size initially? In my case it goes up and goes down even with the pourcent showing:

Here is the code that I am using:

<Image
            source={{uri: 'https://cdn.spacetelescope.org/archives/images/large/heic1509a.jpg'}}
            style={[styles.image]}
            indicator={Progress.Circle}
            indicatorProps={{
                              size: 80,
                              showsText: true,
                            }}
          />

**Comment by oblador** [comment]
This is due to the indeterminate state I believe, you can disable this with a custom `renderIndicator` prop.
