### ISSUE TITLE
Element Type is invalid: expected string (for build-in component)

### ISSUE THREAD

**Issue by waleedarshad-vf** [oblador/react-native-image-progress#28]

**Comment by oblador** [comment]
Do you have any example code/more info about when you get this error?

**Comment by waleedarshad-vf** [comment]
I am using react native 0.27.2. after configuration when i installed build i got error. undefined method for nil class. when i put debugger here and props was undefined

constructor(props) {
  debugger
    super(props);

    this.state = {
      loading: false,
      progress: 0,
      thresholdReached: !props.threshold,
    };
  }

so props.threshold give undefined method threshold for nill class

**Comment by waleedarshad-vf** [comment]
This is the only single library so please update it. i need to use it

**Comment by oblador** [comment]
I tried running example with latest RN and cannot reproduce this. `props` should always be populated unless you're doing something strange like subclassing and not properly calling `super`.

**Comment by waleedarshad-vf** [comment]
@oblador  take a look into this
[
![screenshot_2016-09-26-12-49-08](https://cloud.githubusercontent.com/assets/18189690/18826654/fad20c96-83e7-11e6-950a-0ebb77ce9571.png)
](url)

**Comment by waleedarshad-vf** [comment]
@oblador ?

**Comment by oblador** [comment]
Lol, you're so aggressive.

**Comment by waleedarshad-vf** [comment]
LOl, Sorry there is a pressure to complete application that's why :) i just want to confirm you are paying attention.

**Comment by oblador** [comment]
Well, imagine that I too have work to complete. I'm less inclined to help you out if you don't respect that and post incomplete issues.

**Comment by waleedarshad-vf** [comment]
Sorry bro. post solution some time later when you are fee.  

let me know how can i help you

i just implement your example in listView. 

take a look

this is the code that i have written into my render method

        {this.props.media.type == 'series' ?
                    <View>
                      <RenderPage media={this.props.media} navigator={this.props.navigator}/>
                      <View style={{position: "absolute",right: 15, top: (this.props.media.height/2)-17}}>
                        <TouchableHighlight >
                          <Image style={{height: 30,width:30}} source={require("../assets/white-img- slide.png") }/>
                        </TouchableHighlight>
                      </View>
                    </View>
                    :
                    <View>
                    <Image 
                      source={{ uri: 'http://loremflickr.com/640/480/dog' }} 
                      indicator={ProgressBar} 
                      style={{
                        width: 320, 
                        height: 240, 
                      }}/>

                    </View>
                  }

and just imported 
import Image from 'react-native-image-progress';
import ProgressBar from 'react-native-progress/Bar';

**Comment by waleedarshad-vf** [comment]
Are you still angry with me.  I said sorry. A developer should have cool mind  and must have patience, a lesson learn today :)

**Comment by waleedarshad-vf** [comment]
@oblador would you please let me know if anything i can add as workaround?

**Comment by waleedarshad-vf** [comment]
@oblador have you faced this issue with 0.27.2? i am waiting for your response, would you please

**Comment by bendellarocco** [comment]
+1 I am getting this issue

**Comment by oblador** [comment]
@bendellarocco: Does it work if you use this import statement instead `import * as Progress from 'react-native-progress';` and use `indicator={Progress.Bar}`?

**Comment by bendellarocco** [comment]
The error is no longer displaying.  Thank you for your suggestion @oblador
