### ISSUE TITLE
Progress doesn't work on Indicators

### ISSUE THREAD

**Issue by xuan9230** [oblador/react-native-image-progress#31]
Hi, I've installed both libraries, and am using ProgressCircle:

```
import Image from 'react-native-image-progress';
import ProgressCircle from 'react-native-progress/Circle';

... 

<Image
        source={{ uri: 'http://loremflickr.com/640/480/dog' }}
        indicator={ProgressCircle}
        indicatorProps={{
          showsText: true,
        }}
        style={{
          width: 320,
          height: 240,
        }}
 />
```

But the indicator just spins randomly, no signal of any progress and no text showed as well. After a while the picture is rendered.

I also tried adding `indeterminate: false` into `indicatorProps`. This time it shows text but is locked at 0%; then after a while picture is rendered.

What possibly have I done wrong?

**Comment by Barylskyigb** [comment]
Did you manage to solve this problem?

**Comment by oblador** [comment]
Hi, the `onProgress` event is not supported for android by react-native itself. You might want to give [react-native-fast-image](https://github.com/DylanVann/react-native-fast-image] a try.
