### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by krzysztofp** [oblador/react-native-image-progress#33]
Can you provide caching of images anytime soon? When re-rendering the host component - I don't want to fetch the images again and again in case they are from external source.

**Comment by oblador** [comment]
This is just a composition of the core `Image` component which always have had caching support. You need to make sure the headers you send from your server make the image cacheable.

**Comment by krzysztofp** [comment]
Well, yes - but sometimes back-end returns cache-control with max-age=0 and for that cases I'd likes to use caching mechanism. By the way - it's coming in RN 0.42 http://facebook.github.io/react-native/releases/0.42/docs/images.html#cache-control-ios-only, but only for iOS.

Maybe you can integrate with one of these?
https://github.com/jayesbe/react-native-cacheable-image
https://github.com/remobile/react-native-cache-image

**Comment by oblador** [comment]
Custom image components are now supported in [1.0.0](https://github.com/oblador/react-native-image-progress/releases/tag/v1.0.0). They themselves need to support progress events though :-)

**Comment by hungdev** [comment]
@oblador @cparjaszewski i still get the error. Do you have any solution?
here is my code:
```
import ImageProgress from 'react-native-image-progress';
import Progress from 'react-native-progress/Circle';

            <ImageProgress
              source={{ uri: getImage(mainPhoto) }}
              indicator={Progress}
              indicatorProps={{
                size: 70
              }}
              style={{ ...styles.imageCenter, resizeMode: "cover" }}
            />
            
```
