### ISSUE TITLE
Image with children is deprecated

### ISSUE THREAD

**Issue by iggyfisk** [oblador/react-native-image-progress#38]
In the latest React-Native master commits, rendering children inside an `<Image>` tag throws a yellowbox warning and will soon be removed. A suggested replacement is `<ImageBackground>`, https://github.com/facebook/react-native/commit/9637dd4a1b78d5f6da510b1b4ad10d45d67badbf

**Comment by oblador** [comment]
Hey could you try out current master that should fix this problem? It's a refactor so it might cause some regressions, please report back and I could release this promptly.

**Comment by oblador** [comment]
Ping @iggyfisk

**Comment by oblador** [comment]
Released this in [1.0.0](https://github.com/oblador/react-native-image-progress/releases/tag/v1.0.0). Let me know if you find any regressions.

**Comment by ptomasroos** [comment]
I will check this out when we ship our next release, thanks @oblador !

**Comment by chitrangsinghvi** [comment]
@oblador Hii, I am using 1.0.1, and getting the warning. Is the issue resolved?

**Comment by shuaibird** [comment]
@chitrangsinghvi For the version 1.0.1, the warning would occur if a static image is used. Here is the code snippet of the related stuff:
```javascript
if (!source || !source.uri) {
    // This is not a networked asset so fallback to regular image
    return (
        <ImageComponent source={source} style={style} {...props}>
            {children}
        </ImageComponent>
    );
}
```
