### ISSUE TITLE
Can't change progress state on image error

### ISSUE THREAD

**Issue by nmfzone** [oblador/react-native-image-progress#42]
How to change the `progress` state for example to 100% on image error?

Because I don't see any possible solution on it...

**Comment by oblador** [comment]
Hmm, that seems a bit counter intuitive to me. But it would perhaps make sense to add a way of rendering an error message?

**Comment by oblador** [comment]
Implemented this in [1.0.0](https://github.com/oblador/react-native-image-progress/releases/tag/v1.0.0). Give it a try!
