### ISSUE TITLE
rounded corners with Version 1.0.1

### ISSUE THREAD

**Issue by bemazo** [oblador/react-native-image-progress#44]
with version 0.6.0 the styles was passed to the ImageComponent, with the new version the are overrided:

`style={StyleSheet.absoluteFill}`

how can I create rounded images with the new version?

could it be a solution to use both styles on the image and not on the view:

`style={[StyleSheet.absoluteFill, style]}`

===update===

I just see the pull request #41 and your remark, what about two styles props one for the ViewWrapper and one for the image?

see my pull request #45

**Comment by saghul** [comment]
@oblador Any chance of any of those getting merged? I was trying to use this with react-native-img-cache, but as it stands is not a replacement since rounded corners are not properly respected. 

Thanks a lot for your work!

**Comment by zhengjingt** [comment]
workaround is to add `overflow:hidden` to your image style since style is now applied to its container.

**Comment by llamaluvr** [comment]
Seems like `overflow: 'hidden'` doesn't work in Android, though it also seems like that might be close to no longer being the case (see bottom of the thread- may be fixed in RN 50): https://github.com/facebook/react-native/issues/3198

**Comment by luco** [comment]
@zhengjingt OH doesn't work on Android. Not yet.

**Comment by oblador** [comment]
You can fix this by passing it in the `imageStyle` prop released in [1.1.0](https://github.com/oblador/react-native-image-progress/releases/tag/v1.1.0)
