### ISSUE TITLE
resizeMode not working

### ISSUE THREAD

**Issue by Baptiste-Garcin** [oblador/react-native-image-progress#47]
Hi,

The resizeMode props for image is not working (or maybe, I don't know how to use it)...

![screenshot from 2017-07-11 22-53-33](https://user-images.githubusercontent.com/12398583/28090219-dd234e80-668b-11e7-8be0-a30eb485b663.png)

Here is my component :
`<Image style={ style.image__element }
                  source={{uri: this.props.randomBeer.image_url }}
                  indicatorProps={{
                    color: '#B53409',
                    size: 'large'
                  }}
                  ></Image>`

Here is my style :
`  image__element: {
    flex: 1,
    resizeMode: 'contain'
  }`

Is there an alternative ?

Thanks

**Comment by Baptiste-Garcin** [comment]
Well, I fixed that by introducing a imageProps that contain style destined to ImageComponent.

I would like to submit it as a PR but I can't push my branch... Do you have to allow me somehow ?

It's the first time that I am doing that, I am a bit lost ^^

**Comment by michaelluk** [comment]
Try `
<Image 
style={ style.image__element } 
source={{uri: this.props.randomBeer.image_url }}
indicatorProps={{ color: '#B53409', size: 'large' }} 
resizeMode='contain'
/>`

**Comment by Baptiste-Garcin** [comment]
Hi
I didn't try your solution but I am pretty sure it won't work... anyway, I fixed it and do a pull request (#49)

**Comment by GalaxySystem** [comment]
Oh my god, it's does't work, how bad...

**Comment by jashwanth999** [comment]
it worked!
