### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by Shindraela** [oblador/react-native-image-progress#52]
Hello,

Does the lib support svg files ? I am trying to use the lib `react-native-svg-uri` in the `renderIndicator()` of the `PlaceholderImage()` but it seems that it doesn't work because I receive an error message : `Failed prop type : Invalide prop 'source' supplied to 'Image'`.

Thanks !

**Comment by oblador** [comment]
Unsure, can you post an example in code?

**Comment by Shindraela** [comment]
It was a mistake of mine, sorry !

The source I passed was actually an SVG image, that's a dumb mistake.

Closing this.
