### ISSUE TITLE
[Bug] Progress does not hides with FastImage

### ISSUE THREAD

**Issue by kesha-antonov** [oblador/react-native-image-progress#55]
Hello @oblador !

I've tried custom image FastImage:
<img width="828" alt="screen shot 2017-08-14 at 14 43 17" src="https://user-images.githubusercontent.com/11584712/29270354-10416990-80ff-11e7-86f4-f4b7887af0d9.png">

And I see progress is loading forever (even that image is loaded).
Maybe this related https://github.com/DylanVann/react-native-fast-image/issues/37

<img width="76" alt="screen shot 2017-08-14 at 14 45 01" src="https://user-images.githubusercontent.com/11584712/29270381-2ca348e2-80ff-11e7-8623-f0578cb6129a.png">

**Comment by AlmogRnD** [comment]
+1

**Comment by DannyvanderJagt** [comment]
Same here. It indeed looks like an issue with FastImage, I supposed a solution for the issue and as soon as they agree and we made the adjustments we can fix it here. 

**Temporary fix:**
By adding an `onLoadEnd` prop to your Image, the indicator will work as it's supposed to.

````js
<FastImage
   onLoadEnd={() => {}}
   // Your other props
/>

**Comment by oblador** [comment]
Hi, I'm closing this issue for now and let's track this in the `react-native-fast-image` repo instead. If it turns out it's a bug with this package I'll reopen.

**Comment by AlmogRnD** [comment]
This fixed it for me for now 

onLoadEnd={() => {}}

**Comment by kesha-antonov** [comment]
How about merge this https://github.com/oblador/react-native-image-progress/pull/59/files ?
@oblador 
Will it help with this issue

**Comment by serge66** [comment]
This does not fix me now
onLoadEnd={() => {}}
