### ISSUE TITLE
How to use resizeMode with this plugin

### ISSUE THREAD

**Issue by prancky** [oblador/react-native-image-progress#62]
`resizeMode = {'cover'}`

**Comment by skv-headless** [comment]
I have similar issue I want to use `overlayColor`. @oblador what do you think about adding `imageStyle` property which will be passed to `ImageComponent` here https://github.com/oblador/react-native-image-progress/blob/master/index.js#L195?

BTW @prancky should work with local images

**Comment by skv-headless** [comment]
probably #61 is the same

**Comment by skv-headless** [comment]
@prancky try https://github.com/oblador/react-native-image-progress/issues/61#issuecomment-330416507

**Comment by oblador** [comment]
@skv-headless The cause of this is the refactor needed to support the deprecation of children in `Image`. The problems we're facing affects `ImageBackground` too, and they solve it with `imageStyle`. Personally I feel it's quite inelegant and breaks background compatibility, but so does current implementation. If I merge `imageStyle` I'd have to live with it for a while, so would like to try out some other options, but don't really know if there's any great ones.

**Comment by oblador** [comment]
Maybe now that you can pass a custom `ImageComponent` we could just expose one for `Image` and one for `ImageBackground`.

**Comment by skv-headless** [comment]
@oblador this solution https://github.com/oblador/react-native-image-progress/issues/61#issuecomment-330416507 works for me.

**Comment by fritsvt** [comment]
<Image
      resizeMode="contain"
      indicator={ProgressBar}                
      source={{ uri:  params.image }}
 />

works fine for me

**Comment by duc622** [comment]
> `resizeMode = {'cover'}`

thanks
