### ISSUE TITLE
The progress do not actually track the real progress

### ISSUE THREAD

**Issue by koswarabilly** [oblador/react-native-image-progress#69]
the image was loaded, and shown and the progressbar do not disappear after some times

**Comment by amitava82** [comment]
Same here, indicator shows up after image loaded and does not disappear for some images.

**Comment by anjali14garg** [comment]
Same here

**Comment by arminsal1** [comment]
Same here

**Comment by alshdotme** [comment]
+1

**Comment by ramazanarslan** [comment]
+1

**Comment by mironiasty** [comment]
I had same issue, but looks like this PR #59  helped (at least for now).

**Comment by oblador** [comment]
Should be fixed in [1.1.0](https://github.com/oblador/react-native-image-progress/releases/tag/v1.1.0).
