### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by caphun** [oblador/react-native-image-progress#7]
Do you have plans to support Android?

**Comment by oblador** [comment]
I'd love to, but right now image load events are iOS only.

**Comment by jforaker** [comment]
It has an Android tag on react.parts:

![image](https://cloud.githubusercontent.com/assets/2042031/10700692/7820ec00-798d-11e5-88b7-c70c6986d1fa.png)

**Comment by oblador** [comment]
That's weird, I've only tagged it with `ios` :-/

**Comment by oblador** [comment]
It seems [support is coming](https://github.com/facebook/react-native/pull/3791), hopefully it will be in 0.16.

**Comment by caphun** [comment]
:+1:

**Comment by oblador** [comment]
It's been merged into master now, however it lacks the `ON_PROGRESS` event so only indeterminate spinners will work for now.

**Comment by alvinwoon** [comment]
Weird. The progress indicator won't disappear even after is loaded on android.
```
var ImageP = require('react-native-image-progress');
var Progress = require('react-native-progress/Bar');

<ImageP
      indicator={Progress}
      indicatorProps={{
        borderRadius: 0,
        borderWidth:0,
        height:1,
        color: 'rgb(204,204,204)',
      }}
      style={styles.img}
      resizeMode={Image.resizeMode.cover}
      source={{uri: post.photo}} >
```

**Comment by alvinwoon** [comment]
@oblador is it pushed to NPM yet? Maybe that's why I am not getting it working on android

**Comment by oblador** [comment]
@alvinwoon: I've updated the Example project with an android version. It works, but doesn't show download progress, only loading status. Are you using 0.17?

**Comment by alvinwoon** [comment]
it works now with 0.17 :). Thanks @oblador
