### ISSUE TITLE
Fix progress indicator not removed for static images when using FastImage

### ISSUE THREAD

**Issue by Amurmurmur** [oblador/react-native-image-progress#75]
Upgraded to the latest version v1.1.0, the loading indicator is still showing when image is already in cache.

**Comment by oblador** [comment]
Hi, this is likely due to FastImage not emitting the event properly, can you post an issue there instead?

**Comment by Amurmurmur** [comment]
I think it has been resolved @oblador Sorry for such delay.
Btw, thank you so much for a react-native-vector-icons library, do you plan to update those icons to the latest ones like for example fontawesome is already at 5.0 and Material icons and MaterialCommunity icons have added/updated so many icons ? :)
