### ISSUE TITLE
Issue with StyleSheet.create()

### ISSUE THREAD

**Issue by lifeiscontent** [oblador/react-native-image-progress#79]
when accessing properties from StyleSheet.create() it will return a number instead of an object. in the propType imageStyle its expecting an object which isn't 100% compatible. you should also say it can be a number.

**Comment by oblador** [comment]
Hi, the prop types already says `PropTypes.any`, maybe you're on an old version?

**Comment by antoinegrelard** [comment]
I think he's talking about the imageStyle prop, which still has a PropTypes.object propType. I have the same issue and it's on the imageStyle prop that it is happening :)
