### ISSUE TITLE
Compatibility with react-native-lightbox

### ISSUE THREAD

**Issue by JonathanWi** [oblador/react-native-image-progress#8]
Hey!

First, I just realised you were responsible for at least half of the components I use on my current project, and they are all awesome, so thank you deeply!

Funnily enough, I have a very small issue when combining the image progress and your awesome lightbox : When you tap on the Image to "grow", you can see the loader in front of the image for something like 300ms, and then disappear.

This is obviously not a pressing issue, and more of a heads up, I'm sure it's nothing!

Again thanks for your absolutely wonderful work, I'll start following what you do, awesome you!

**Comment by oblador** [comment]
Thanks for the report and kind words :blush:!

Looked into it and it appears to be an old workaround for RN versions that I recently deprecated support or anyway. Should be fixed now and released it in version [0.3.1](https://github.com/oblador/react-native-image-progress/releases/tag/v0.3.1).

**Comment by JonathanWi** [comment]
Just installed it, works perfectly. Thanks for such a quick reply & fix!

**Comment by oblador** [comment]
:+1:

**Comment by oblador** [comment]
Out of curiosity, what are you building?

**Comment by JonathanWi** [comment]
Nothing big, I come from a heavy angular background, former Ionic app addict, trying my hand at React and React native. I fell in love with it, so I wanted to put in practice what I was learning. You can find the "project" [here](https://github.com/JonathanWi/Stories), which is basically a [/r/writingPrompts](https://www.reddit.com/r/writingprompts) better reader.

[Bonus gif of the app](http://i.imgur.com/Pytp13G.gif)

**Comment by oblador** [comment]
Wow, that looks really good! Let me know when it's in the AppStore :-)

**Comment by JonathanWi** [comment]
I sure will, thanks!
