### ISSUE TITLE
[feature request] Do not show a loadingIndicator if the request happens within a short amount of time

### ISSUE THREAD

**Issue by ms88privat** [oblador/react-native-image-progress#9]
Could you please provide an implementation with a threshold property? If the request finished before the threshold is reached, it will not show any loadingIndicator at all.

In my case it looks very strange when I'm going to show a'lot of cached images. It will flicker the indicator in and out.

I could try to implement it myself, if I got some time next week. What do you think about this feature?

Thanks a'lot!

**Comment by oblador** [comment]
Are you on latest? It has a bugfix concerning cached images. Sounds like a good feature no matter what and I'll most likely merge :-)

**Comment by ms88privat** [comment]
Hm. Yes, I do have the latest version installed. I'm not sure what is happening then. All of the 10~images are loaded equally fast. 
When I add a new Image, it loads noticeable longer and the indicator is nice to have.

**Comment by oblador** [comment]
Yeah, I think it might be different depending on from which cache they are coming from (cold start vs reuse of image source). So I guess the threshold should be on by default then. Will do you a PR?

**Comment by oblador** [comment]
I'm working on this and a major refactor of the component, no PR necessary!
