### ISSUE TITLE
🐞resizeMode with `react-native-fast-image` is not working!

### ISSUE THREAD

**Issue by hackrx** [oblador/react-native-image-progress#92]
I am using `react-native-image-progress` with `react-native-fast-image` and with this I am using `ResizeMode` method inside `imageStyle` as a prop but it is not working,  

**To Reproduce**
```
import {createImageProgress} from 'react-native-image-progress';
import FastImage from 'react-native-fast-image';

const Image = createImageProgress(FastImage);
export default class ImageLoader extends Component {
constructor(){
state = {
photo: this.props.photo,
resizeMode: this.props.resizeMode,
}
}
render() {

return(
<View>
 <Image
            source={{
              uri: this.state.photo,
              cache: FastImage.cacheControl.immutable,
            }} 
            imageStyle={{
              resizeMode: this.state.resizeMode,
             
            }}
            style={{
              height: 280,
              width: '100%',
            }}
            indicator={Progress.Circle}
            indicatorProps={{
              size: 80,
            }}
          />
</View>
)}
};
```

**Expected behavior**
I am expecting the effect of `resizeMode` but it is not working.

**Comment by mpochron** [comment]
I am having issue too.

**Comment by mpochron** [comment]
resizeMode doesn't work for imageStyle, you can just put the attribute `resizeMode={FastImage.resizeMode.contains}` for the parent element.

**Comment by hackrx** [comment]
> I found the solution
> 
> resizeMode doesn't work for imageStyle, you can just put the attribute `resizeMode={FastImage.resizeMode.contains}` for the element which has been used by createImageProgress.
Let me check and then I will close this issue

**Comment by hackrx** [comment]
Thanks @mpochron  it did work, today I stumbled across this issue again and this issue helped me 😄 .
