### ISSUE TITLE
@TypeScript

### ISSUE THREAD

**Issue by EmersonGarrido** [oblador/react-native-image-progress#93]
Cannot find module 'react-native-image-progress' or its corresponding type declarations.

is lib not declaretions types... what?

**Comment by mpochron** [comment]
index.d.ts
```

declare module 'react-native-image-progress' {
  
  import { ComponentType } from "react";

  export function createImageProgress(params: any): ComponentType<any>

}
```

Works for me.

**Comment by magnusfernandes** [comment]
+1

**Comment by thiagog3** [comment]
+1

**Comment by swalahamani** [comment]
+1

**Comment by dmk3141618** [comment]
export const createImageProgress = ImageComponent =&gt;  class ImageProgress extends Component {
...
export default createImageProgress(Image);

=>

export default class ImageProgress extends Component {


And add this index.d.ts file with same directory named ImageProgress.
so 
ImageProgress/index.js (js source file)
ImageProgress/index.d.ts


And index.d.ts file is like below.


import React, {Component, ComponentProps} from 'react';
import {ViewStyle, ImageStyle, ActivityIndicator} from 'react-native';
export interface ImageProgressProps {
  children?: React.ReactNode;
  errorContainerStyle?: ViewStyle;
  indicatorContainerStyle?: ViewStyle;
  indicatorProps?: ComponentProps<typeof ActivityIndicator>;
  source?: any;
  style?: ViewStyle;
  imageStyle?: ImageStyle;
  threshold?: number;
}
export default class ImageProgress extends Component<ImageProgressProps> {}

**Comment by dmk3141618** [comment]
import React, {Component, ComponentProps} from 'react';
import {
  ViewStyle,
  ImageStyle,
  ActivityIndicator,
  ImageSourcePropType,
  StyleProp,
} from 'react-native';
export interface ImageProgressProps {
  children?: React.ReactNode;
  errorContainerStyle?: StyleProp<ViewStyle>;
  indicatorContainerStyle?: StyleProp<ViewStyle>;
  indicatorProps?: ComponentProps<typeof ActivityIndicator>;
  source?: ImageSourcePropType;
  style?: StyleProp<ViewStyle>;
  imageStyle?: StyleProp<ImageStyle>;
  threshold?: number;
}
export default class ImageProgress extends Component<ImageProgressProps> {}

**Comment by i-mighty** [comment]
> import React, {Component, ComponentProps} from 'react';
> import {
> ViewStyle,
> ImageStyle,
> ActivityIndicator,
> ImageSourcePropType,
> StyleProp,
> } from 'react-native';
> export interface ImageProgressProps {
> children?: React.ReactNode;
> errorContainerStyle?: StyleProp;
> indicatorContainerStyle?: StyleProp;
> indicatorProps?: ComponentProps;
> source?: ImageSourcePropType;
> style?: StyleProp;
> imageStyle?: StyleProp;
> threshold?: number;
> }
> export default class ImageProgress extends Component {}

Could you reformat this?
Looks like this may be the right fix

**Comment by GittyAjay** [comment]
`npm i react-native-progress`

work for me

**Comment by oblador** [comment]
1.2.0 includes typescript definitions 👍
