### ISSUE TITLE
Invariant Violation: ART has been removed from React Native

### ISSUE THREAD

**Issue by bockc** [oblador/react-native-image-progress#94]
Hello,
We've been using this package for quite a long time now and it works really well.

I just upgraded react-native from 0.60.5 to 0.63.3 and I am now getting exceptions from your package.
Since ART has been removed from react-native and has now its own standalone package, this package should be updated accordingly. We're obviously using version 1.1.1 right now.

I searched for any mention/import of ART in your package and its dependencies but unfortunately I found nothing and we're now forced to disable it in our app. Could you check where ART is used and update its import in the package please ?

**Comment by pbassut** [comment]
@bockc Having the same issue here. So you had no way out but removing from your app?

@oblador Any version we could downgrade to in order to get this going?

**Comment by pbassut** [comment]
I noticed it only fails when you use the `Progress.Pie` from the example.

**Comment by bockc** [comment]
@pbassut Yes, we didn't find any fix for this yet, so we just commented all imports and code related to this package unfortunately. We're still waiting for infos from @oblador

**Comment by oblador** [comment]
Update `react-native-progress` package and add `react-native-svg` dependency.
