### ISSUE TITLE
Bearer token error

### ISSUE THREAD

**Issue by silverax** [oblador/react-native-image-progress#97]
We are trying to load protected images with this code:
`

	<Image
		onPress={() => {
		}}
		source={{
			uri: uri,
			headers: {
				Authorization: `Bearer ${token}`,
			},
		}}

		onError={({ nativeEvent: { error } }) => {
			console.log("getImageContent error:")
			console.log(error)

		}}

		indicator={ProgressBar}
		indicatorProps={{
			size: 80,
			borderWidth: 0,
			color: "#010087",
		}}
		resizeMode="contain"
		style={{
			marginTop: 20,
			width: Dimensions.get("window").width,
			height: Dimensions.get("window").height - 200,
			backgroundColor: 'red',
		}}
	/>

`

But the server can not access the bearer and only receive this headers:
[cookie] 
[accept-encoding] 
[connection] 
[host] 
[user-agent]

**Comment by silverax** [comment]
Also the error returned is only the status, is there a way to get the full response?

**Comment by oblador** [comment]
This component extends the built in Image component by default, so look into that component for APIs to debug it (or use your own custom component with `createImageProgress`.
