### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by swalahamani** [oblador/react-native-image-progress#98]
Hi @oblador,

Thank you 🙏🏼  so much for all your efforts 🚀  to the open-source react native libraries. I owe you each day as a React Native developer!

I would like to know the maintenance status of this library to use in one of my projects.

**Comment by Mihai-github** [comment]
+1

**Comment by Niweera** [comment]
Hi @swalahamani, I was wondering about this too, and I went through the code and it seems a little bit old for 2021. I updated it to be compatible with the latest React (^17.0.x) versions and I'll make a pull request soon.

-cc @oblador 🙏

**Comment by swalahamani** [comment]
That would be great @Niweera 👍

**Comment by oblador** [comment]
1.2.0 was just released with bug fixes and type script support 👍

**Comment by swalahamani** [comment]
Thank you @oblador 🙏  🚀
