### ISSUE TITLE
Update the package for the latest React dependencies (^v17.0.x)

### ISSUE THREAD

**Issue by Niweera** [oblador/react-native-image-progress#99]
Hi @oblador,

It seems that this package is not maintaining for the last few years. I updated the package to support the latest React dependencies by converting the Class based component to a Functional component. I'll make a pull request regarding this.

Thanks in advance. 🙏

**Comment by oblador** [comment]
I updated the example project in #104 and it works fine with React 17, maybe you're referring to React 18?

**Comment by Niweera** [comment]
May be this issue will be invalid from now on. I'll close this. Thank you for your time.
